Release Unit 6
icssc/fellowship pull request #35
Opened 2022-04-25 20:49 UTC by ramanxg

Closes #6 

Release Unit 6. 

TODO: 
Might record a new lecture video.

2022-04-26 05:55 UTC, ChaseC99 requested changes

2022-04-26 15:51 UTC, ramanxg commented on docs/unit7.mdx
> +---
Fixed.

2022-04-26 16:23 UTC, ramanxg commented on docs/unit6.mdx
> +Variables are dynamically-typed, meaning, they don't have a type (like in Python). Undefined variables have the value `undefined`. We use `let` and `const` to define variables.
Added.

2022-04-26 16:24 UTC, ramanxg commented on docs/unit6.mdx
> +for (let x = 0; x < 5; x++) {
Added for each loops as well as for-of loops.

2022-04-26 16:24 UTC, ramanxg commented on docs/unit6.mdx
> +### Functions
This was included, but I gave arrow functions its own section and more descriptions to anonymous functions.

2022-04-26 16:24 UTC, ramanxg commented on docs/unit6.mdx
> +### Arrays
Added. Let me know what you think.

2022-04-29 00:33 UTC, ramanxg commented
I've added an assignment for Unit 6. The solutions are in the google drive. Also moved the installation of Node.js, to Unit 6, so they can set it up here, and run the program on their own computer.

2022-04-29 03:52 UTC, ChaseC99 commented
Awesome! I'm also going to setup a github repo for them to fork to do the javascript problems. It'll be good practice working with forking.

2022-04-29 20:42 UTC, ramanxg commented
> Awesome! I'm also going to setup a github repo for them to fork to do the javascript problems. It'll be good practice working with forking.

Thanks! When you finish, can you add it to the guide? I'll record a new lecture this weekend for the unit.

2022-05-02 11:26 UTC, ChaseC99 commented on docs/unit6.mdx
> +
TODO: Should probably go into greater detail here

2022-05-03 19:07 UTC, ChaseC99 approved these changes

2022-05-03 19:07 UTC, merged